######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 26 18:24:31 2017
######################################################################

TEMPLATE = app
TARGET = my_qt_exp
DEPENDPATH += .
INCLUDEPATH += .

# my config
DESTDIR = ../bin
OBJECTS_DIR = ../obj
CONFIG += qt warn_on debug release
VPATH += ../src

# Input
HEADERS += mainwnd.h work_thread.h
SOURCES += main.cpp mainwnd.cpp
